// Build the distributable userscript and web-extension from the ESM sources.
//
// No bundler: the two source modules are dependency-free and self-contained,
// so we concatenate them (stripping import/export), inline the theme CSS, and
// wrap the result in an IIFE. Outputs:
//   dist/eucalypt-github.user.js   — Tampermonkey/Violentmonkey userscript
//   extension/content.js           — MV3 content script (same body)
//   extension/manifest.json        — MV3 manifest
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(here, p), "utf8");

const VERSION = JSON.parse(read("package.json")).version;

function strip(src) {
  return src
    .replace(/^import\s+[^;]*;\s*$/gm, "") // drop inter-module imports
    .replace(/^export\s+/gm, ""); // drop export keywords
}

const core = strip(read("src/eucalypt-highlight.mjs"));
const dom = strip(read("src/github-dom.mjs"));
const css = read("src/theme.css");

const body = `(function () {
  "use strict";
  const THEME_CSS = ${JSON.stringify(css)};

// ===== eucalypt-highlight.mjs =====
${core}
// ===== github-dom.mjs =====
${dom}

  initEucalyptHighlighter({ css: THEME_CSS });
})();
`;

const banner = (kind) =>
  `// Eucalypt syntax highlighting for the GitHub web UI — ${kind}.\n` +
  `// GENERATED by build.mjs from src/*.mjs and src/theme.css — do not edit by hand.\n` +
  `// Source: https://github.com/curvelogic/eucalypt/tree/master/editors/github-highlighter\n`;

const userscriptHeader = `// ==UserScript==
// @name         Eucalypt syntax highlighting for GitHub
// @namespace    https://github.com/curvelogic/eucalypt
// @version      ${VERSION}
// @description  Syntax-highlight Eucalypt (.eu) files in GitHub pull-request diffs, commits and blobs.
// @author       Curve Logic
// @match        https://github.com/*
// @run-at       document-idle
// @grant        none
// @homepageURL  https://github.com/curvelogic/eucalypt/tree/master/editors/github-highlighter
// @downloadURL  https://raw.githubusercontent.com/curvelogic/eucalypt/master/editors/github-highlighter/dist/eucalypt-github.user.js
// @updateURL    https://raw.githubusercontent.com/curvelogic/eucalypt/master/editors/github-highlighter/dist/eucalypt-github.user.js
// ==/UserScript==
`;

mkdirSync(join(here, "dist"), { recursive: true });
mkdirSync(join(here, "extension"), { recursive: true });

writeFileSync(
  join(here, "dist/eucalypt-github.user.js"),
  userscriptHeader + "\n" + banner("userscript") + body
);

writeFileSync(join(here, "extension/content.js"), banner("web extension") + body);
writeFileSync(join(here, "extension/theme.css"), css);

writeFileSync(
  join(here, "extension/manifest.json"),
  JSON.stringify(
    {
      manifest_version: 3,
      name: "Eucalypt syntax highlighting for GitHub",
      version: VERSION,
      description:
        "Syntax-highlight Eucalypt (.eu) files in GitHub pull-request diffs, commits and blobs.",
      content_scripts: [
        {
          matches: ["https://github.com/*"],
          js: ["content.js"],
          css: ["theme.css"],
          run_at: "document_idle",
        },
      ],
    },
    null,
    2
  ) + "\n"
);

// Sanity: the bundle must be valid JS.
new Function(body);

console.log("built dist/eucalypt-github.user.js and extension/ (v%s)", VERSION);
