// Generate src/grammar-tables.mjs from the canonical TextMate grammar.
//
// The highlighter's prelude and keyword tables must match the rest of the
// toolchain. Rather than hand-copying them (a fourth place for the prelude
// list to drift), we extract them at build time from the word alternations in
// editors/vscode/syntaxes/eucalypt.tmLanguage.json — the same grammar VS Code
// and Shiki use. `npm run build` runs this first; a test asserts the committed
// table stays in sync.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const grammarPath = join(here, "..", "vscode", "syntaxes", "eucalypt.tmLanguage.json");

// Pull the word list out of a `(?<!…)(?:a|b|c)(?!…)` style match string. The
// only `(?:…)` group in these patterns is the alternation itself; word
// boundaries are expressed as look-around char classes that contain no `)`.
function wordsFrom(match) {
  const m = match.match(/\(\?:([^)]*)\)/);
  if (!m) throw new Error(`no alternation group found in: ${match}`);
  // Undo regex escaping (e.g. `all-true\?` -> `all-true?`).
  return m[1].split("|").map((w) => w.replace(/\\(.)/g, "$1"));
}

export function computeTables() {
  const grammar = JSON.parse(readFileSync(grammarPath, "utf8"));
  return {
    keywords: wordsFrom(grammar.repository.keyword.match),
    prelude: wordsFrom(grammar.repository.prelude.match),
  };
}

export function generate() {
  const { keywords, prelude } = computeTables();
  const arr = (a) => JSON.stringify(a, null, 2);
  const out = `// GENERATED by gen-tables.mjs from
// editors/vscode/syntaxes/eucalypt.tmLanguage.json — DO NOT EDIT BY HAND.
// Run \`npm run gen\` (or \`npm run build\`) to regenerate after the grammar's
// prelude/keyword lists change. Keeps the highlighter in lock-step with the
// canonical TextMate grammar that VS Code and Shiki use.

export const KEYWORD_WORDS = ${arr(keywords)};

export const PRELUDE_WORDS = ${arr(prelude)};

export const KEYWORDS = new Set(KEYWORD_WORDS);
export const PRELUDE = new Set(PRELUDE_WORDS);
`;
  writeFileSync(join(here, "src", "grammar-tables.mjs"), out);
  return { keywords, prelude };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { keywords, prelude } = generate();
  console.log(
    "generated src/grammar-tables.mjs: %d keywords, %d prelude functions",
    keywords.length,
    prelude.length
  );
}
