# Configuration for git-changelog

conventions:
  categories:
    - {tag: "break", title: "Breaking Changes"}
    - {tag: "feature", title: "Features"}
    - {tag: "fix", title: "Fixes"}
    - {tag: "perf", title: "Performance Improvements"}

  scopes:
    - {tag: "", title: ""}
    - {tag: "api", title: "API"}
    - {tag: "doc", title: "Documentation"}
