[package]
name = "eucalypt"
version = "0.2.0"
authors = ["gmorpheme <github@gmorpheme.net>"]
edition = "2018"

[build-dependencies]
lalrpop = { version = "0.19.5", features = ["lexer"] }

[dependencies]
regex = "1.4.5"
matches = "0.1.8"
codespan = "0.11.1"
codespan-reporting = "0.11.1"
lalrpop-util = "0.19.5"
serde_json = "1.0.64"
yaml-rust = "0.4.5"
unic-ucd-category = "0.9.0"
itertools = "0.10.0"
thiserror = "1.0.24"
structopt = "0.3.21"
url = "2.2.1"
pretty = "0.10.0"
moniker = { git = "https://github.com/curvelogic/moniker", rev = "c620b2a69d6cad4724cba07775ed65a7ae556c9c" }
indexmap = "1.6.2"
petgraph = "0.5.1"
atty = "0.2"
csv = "1.1.6"
lazy_static = "1.4.0"
chrono = "0.4.19"
bitflags = "1.2.1"
quick-xml = "0.22.0"
chrono-tz = "0.5.3"
toml = { version = "0.5.8", features = ["preserve_order"] }
dirs = "3.0.2"
html5ever = "0.25.1"
bacon_rajan_cc = "0.3.2"
