name:                eucalypt
version:             0.1.2.0
github:              "curvelogic/eucalypt"
license:             MIT
author:              "Greg Hawkins"
maintainer:          "greg@curvelogic.co.uk"
copyright:           "2018 Greg Hawkins"

extra-source-files:
- README.md
- lib/prelude.eu

synopsis:            Haskell implementation of Eucalypt tooling and language
description:         Please see the README on Github at <https://github.com/curvelogic/eucalypt#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-pretty
    - array
    - bound
    - bytestring
    - cassava
    - comonad
    - conduit
    - containers
    - insert-ordered-containers
    - deepseq
    - deriving-compat
    - directory
    - exceptions
    - filepath
    - file-embed
    - hashable
    - lens
    - libyaml
    - mtl
    - network-uri
    - optparse-applicative
    - megaparsec
    - monad-loops
    - mtl
    - path
    - pretty
    - primitive
    - QuickCheck
    - regex-pcre-builtin
    - pcre-heavy
    - resourcet
    - safe
    - safe-exceptions
    - scientific
    - split
    - strict
    - symbol
    - text
    - time
    - tomland
    - transformers
    - typed-process
    - unix
    - unordered-containers
    - vector
    - yaml

executables:
  eu:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eucalypt
    - optparse-applicative
    - directory
    - filepath
    - path
    - network-uri

tests:
  eucalypt-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - aeson
      - aeson-pretty
      - bound
      - bytestring
      - conduit
      - containers
      - eucalypt
      - hspec
      - hspec-megaparsec
      - libyaml
      - megaparsec
      - monad-loops
      - mtl
      - network-uri
      - path
      - pretty
      - scientific
      - silently
      - symbol
      - time
      - text
      - tomland
      - unordered-containers
      - vector
      - yaml
