version: 2
jobs:

  # Build and unit test the eu executable
  build:
    docker:
      - image: curvelogic/docker-circleci-haskell
    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ checksum "package.yaml" }}
            - cache

      - run:
          name: Update PATH to allow stack-built tools
          command: |
            echo 'export PATH=.local/bin:$PATH' >> $BASH_ENV
            echo 'export STACK_DIST_DIR=$(stack path --dist-dir)' >> $BASH_ENV
            echo 'export STACK_LOCAL_HPC_ROOT=$(stack path --local-hpc-root)' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install HLint
          command: stack install hlint

      - run:
          name: Build
          command: stack build --pedantic

      - save_cache:
          paths:
            - ~/.stack
          key: cache-{{ checksum "package.yaml" }}

      - run:
          name: Run unit tests & coverage
          command: stack test --no-terminal --coverage

      - run:
          name: Run HLint
          command: hlint .

      - run:
          name: Echo stack path configuration
          command: stack path --dist-dir

      - persist_to_workspace:
          root: .stack-work
          paths:
            - dist

      - run:
          name: Prepare artifacts
          command: |
            mkdir -p /tmp/artifacts
            copy $STACK_DIST_DIR /tmp/artifacts/dist
            copy $STACK_LOCAL_HPC_ROOT /tmp/artifacts/coverage

      - store_artifacts:
          path: /tmp/artifacts

  # Test against the eucalypt test suite
  acceptance:

    machine: true

    steps:
      - attach_workspace:
          at: .stack-work
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker run -v .stack-work:/tmp/workspace -e EXECUTABLE=/tmp/workspace/dist/x86_64-linux/Cabal-2.0.1.0/eu curvelogic/eucalypt-test-harness:latest

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: curvelogic-docker-hub
      - acceptance:
          context: curvelogic-docker-hub
          requires:
            - build
