version: 2
jobs:

  # Build and unit test the eu executable
  build:
    docker:
      - image: curvelogic/docker-circleci-haskell
    steps:
      - checkout

      - restore_cache:
          key: cache

      - run:
          name: Update PATH to allow stack-built tools
          command: |
            echo 'export PATH=.local/bin:$PATH' >> $BASH_ENV
            echo 'export STACK_DIST_DIR=$(stack path --dist-dir)' >> $BASH_ENV
            echo 'export STACK_LOCAL_HPC_DIR=$(stack path --local-hpc-dir)' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install HLint
          command: stack install hlint

      - run:
          name: Build
          command: stack build --pedantic

      - save_cache:
          paths:
            - ~/.stack
          key: cache

      - run:
          name: Run unit tests & coverage
          command: stack test --no-terminal --coverage

      - run:
          name: Run HLint
          command: hlint .

      - run:
          name: Echo stack path configuration
          command: stack path --dist-dir

      - persist_to_workspace:
          root: .stack-work
          paths:
            - dist

  # Test against the eucalypt test suite
  acceptance:

    machine: true

    steps:
      - attach_workspace:
          at: .stack-work
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker run -v .stack-work:/tmp/workspace -e EXECUTABLE=/tmp/workspace/dist/x86_64-linux/Cabal-2.0.1.0/eu curvelogic/eucalypt-test-harness:latest
