version: 2
jobs:
  build:
    docker:
      - image: curvelogic/docker-circleci-haskell
    steps:
      - checkout

      - restore_cache:
          key: cache

      - run: stack install hlint

      - run: stack build --pedantic

      - save_cache:
          paths:
            - ~/.stack
          key: cache

      - run: stack test --no-terminal --coverage

      - run: hlint .
