version: 2
jobs:

  # Build and unit test the eu executable
  build:
    docker:
      - image: curvelogic/docker-circleci-haskell
    steps:
      - checkout

      - restore_cache:
          key: cache

      - run: stack install hlint

      - run: stack build --pedantic

      - save_cache:
          paths:
            - ~/.stack
          key: cache

      - run: stack test --no-terminal --coverage

      - run: hlint .

      - run: stack path --dist-dir

      - persist_to_workspace:
          root: .stack-work
          paths:
            - dist

  # Test against the eucalypt test suite
  acceptance:

    machine: true

    steps:
      - attach_workspace:
          at: .stack-work
      - run: docker run -v .stack-work:/tmp/workspace -e EXECUTABLE=/tmp/workspace curvelogic/eucalypt-test-harness:latest
