#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_COLON = 3,
  anon_sym_BQUOTE = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_LPAREN2 = 8,
  sym_number = 9,
  anon_sym_DQUOTE = 10,
  sym_string_content = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  aux_sym_interpolation_content_token1 = 14,
  anon_sym_DOT = 15,
  sym_format_spec = 16,
  anon_sym_LBRACE_LBRACE = 17,
  anon_sym_RBRACE_RBRACE = 18,
  aux_sym_escape_sequence_token1 = 19,
  anon_sym_SQUOTE = 20,
  aux_sym_quoted_identifier_token1 = 21,
  sym_operator = 22,
  aux_sym_anaphor_token1 = 23,
  aux_sym_anaphor_token2 = 24,
  anon_sym_LBRACK = 25,
  anon_sym_RBRACK = 26,
  sym__declaration_end = 27,
  sym_source_file = 28,
  sym_unit_metadata = 29,
  sym_declaration = 30,
  sym_metadata = 31,
  sym__meta_value = 32,
  sym_declaration_head = 33,
  sym_operator_declaration = 34,
  sym_parameter_list = 35,
  sym_soup = 36,
  sym__element = 37,
  sym_paren_expr = 38,
  sym_application = 39,
  sym_argument_list = 40,
  sym_literal = 41,
  sym_string = 42,
  sym_interpolation = 43,
  sym_interpolation_content = 44,
  sym_dotted_reference = 45,
  sym_escape_sequence = 46,
  sym_symbol = 47,
  sym_name = 48,
  sym_quoted_identifier = 49,
  sym_anaphor = 50,
  sym_block = 51,
  sym_list = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_parameter_list_repeat1 = 54,
  aux_sym_soup_repeat1 = 55,
  aux_sym_argument_list_repeat1 = 56,
  aux_sym_string_repeat1 = 57,
  aux_sym_dotted_reference_repeat1 = 58,
  aux_sym_block_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN2] = "(",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_interpolation_content_token1] = "interpolation_content_token1",
  [anon_sym_DOT] = ".",
  [sym_format_spec] = "format_spec",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_identifier_token1] = "quoted_identifier_token1",
  [sym_operator] = "operator",
  [aux_sym_anaphor_token1] = "anaphor_token1",
  [aux_sym_anaphor_token2] = "anaphor_token2",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__declaration_end] = "_declaration_end",
  [sym_source_file] = "source_file",
  [sym_unit_metadata] = "unit_metadata",
  [sym_declaration] = "declaration",
  [sym_metadata] = "metadata",
  [sym__meta_value] = "_meta_value",
  [sym_declaration_head] = "declaration_head",
  [sym_operator_declaration] = "operator_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_soup] = "soup",
  [sym__element] = "_element",
  [sym_paren_expr] = "paren_expr",
  [sym_application] = "application",
  [sym_argument_list] = "argument_list",
  [sym_literal] = "literal",
  [sym_string] = "string",
  [sym_interpolation] = "interpolation",
  [sym_interpolation_content] = "interpolation_content",
  [sym_dotted_reference] = "dotted_reference",
  [sym_escape_sequence] = "escape_sequence",
  [sym_symbol] = "symbol",
  [sym_name] = "name",
  [sym_quoted_identifier] = "quoted_identifier",
  [sym_anaphor] = "anaphor",
  [sym_block] = "block",
  [sym_list] = "list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_soup_repeat1] = "soup_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_dotted_reference_repeat1] = "dotted_reference_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_interpolation_content_token1] = aux_sym_interpolation_content_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_format_spec] = sym_format_spec,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_identifier_token1] = aux_sym_quoted_identifier_token1,
  [sym_operator] = sym_operator,
  [aux_sym_anaphor_token1] = aux_sym_anaphor_token1,
  [aux_sym_anaphor_token2] = aux_sym_anaphor_token2,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__declaration_end] = sym__declaration_end,
  [sym_source_file] = sym_source_file,
  [sym_unit_metadata] = sym_unit_metadata,
  [sym_declaration] = sym_declaration,
  [sym_metadata] = sym_metadata,
  [sym__meta_value] = sym__meta_value,
  [sym_declaration_head] = sym_declaration_head,
  [sym_operator_declaration] = sym_operator_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_soup] = sym_soup,
  [sym__element] = sym__element,
  [sym_paren_expr] = sym_paren_expr,
  [sym_application] = sym_application,
  [sym_argument_list] = sym_argument_list,
  [sym_literal] = sym_literal,
  [sym_string] = sym_string,
  [sym_interpolation] = sym_interpolation,
  [sym_interpolation_content] = sym_interpolation_content,
  [sym_dotted_reference] = sym_dotted_reference,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_symbol] = sym_symbol,
  [sym_name] = sym_name,
  [sym_quoted_identifier] = sym_quoted_identifier,
  [sym_anaphor] = sym_anaphor,
  [sym_block] = sym_block,
  [sym_list] = sym_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_soup_repeat1] = aux_sym_soup_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_dotted_reference_repeat1] = aux_sym_dotted_reference_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_interpolation_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_format_spec] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_anaphor_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_anaphor_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__declaration_end] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym__meta_value] = {
    .visible = false,
    .named = true,
  },
  [sym_declaration_head] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_soup] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation_content] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_anaphor] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_soup_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_reference_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 21,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 37,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 41,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 19,
  [60] = 60,
  [61] = 61,
  [62] = 16,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 98,
  [112] = 109,
};

static TSCharacterRange sym_identifier_character_set_1[] = {
  {'$', '$'}, {'?', '?'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'}, {0xc0, 0x2af}, {0x370, 0x4ff}, {0x1f00, 0x1fff},
  {0x2022, 0x2022},
};

static TSCharacterRange sym_identifier_character_set_2[] = {
  {'!', '!'}, {'$', '$'}, {'*', '*'}, {'-', '-'}, {'0', '9'}, {'?', '?'}, {'A', 'Z'}, {'_', '_'},
  {'a', 'z'}, {0xc0, 0x2af}, {0x370, 0x4ff}, {0x1f00, 0x1fff}, {0x2022, 0x2022},
};

static TSCharacterRange sym_operator_character_set_1[] = {
  {'!', '!'}, {'%', '&'}, {'*', '+'}, {'-', '/'}, {';', '>'}, {'@', '@'}, {'^', '^'}, {'|', '|'},
  {'~', '~'}, {0xa1, 0xa1}, {0xa3, 0xa3}, {0xac, 0xac}, {0xb1, 0xb1}, {0xd7, 0xd7}, {0xf7, 0xf7}, {0x3c0, 0x3c0},
  {0x20ac, 0x20ac}, {0x2190, 0x21bb}, {0x21d0, 0x21ea}, {0x2200, 0x2200}, {0x2202, 0x2203}, {0x2205, 0x2205}, {0x2207, 0x2209}, {0x220f, 0x220f},
  {0x2211, 0x2211}, {0x2218, 0x2218}, {0x221a, 0x221a}, {0x221e, 0x221e}, {0x2227, 0x222b}, {0x223c, 0x223c}, {0x2248, 0x2248}, {0x2260, 0x2261},
  {0x2264, 0x2265}, {0x226a, 0x226b}, {0x2282, 0x2283}, {0x2286, 0x2287}, {0x2295, 0x2295}, {0x2297, 0x2297}, {0x2299, 0x2299}, {0x229e, 0x229f},
  {0x22a1, 0x22a5}, {0x22a8, 0x22a9}, {0x22b8, 0x22b8}, {0x22ba, 0x22ba}, {0x22c0, 0x22c6}, {0x22c8, 0x22ca}, {0x22ee, 0x22f1}, {0x2308, 0x230b},
  {0x25b3, 0x25b3}, {0x25bd, 0x25bd}, {0x27e6, 0x27eb}, {0x27f5, 0x27ff}, {0x2a08, 0x2a08},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 25,
        '#', 16,
        '\'', 40,
        '(', 22,
        ')', 20,
        ',', 21,
        '-', 43,
        '.', 32,
        ':', 17,
        '[', 45,
        '\\', 8,
        ']', 46,
        '_', 38,
        '`', 18,
        '{', 29,
        '}', 30,
        0x2022, 38,
        0xd7, 37,
        0xf7, 37,
        0x3c0, 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (set_contains(sym_operator_character_set_1, 53, lookahead)) ADVANCE(44);
      if (('$' <= lookahead && lookahead <= 'z') ||
          (0xc0 <= lookahead && lookahead <= 0x2af) ||
          (0x370 <= lookahead && lookahead <= 0x4ff) ||
          (0x1f00 <= lookahead && lookahead <= 0x1fff)) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '}') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '_') ADVANCE(38);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead == 0x2022) ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead == '$' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xc0 <= lookahead && lookahead <= 0x2af) ||
          (0x370 <= lookahead && lookahead <= 0x4ff) ||
          (0x1f00 <= lookahead && lookahead <= 0x1fff)) ADVANCE(39);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == 0xd7 ||
          lookahead == 0xf7 ||
          lookahead == 0x3c0) ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (set_contains(sym_operator_character_set_1, 53, lookahead)) ADVANCE(44);
      if (set_contains(sym_identifier_character_set_1, 9, lookahead)) ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (set_contains(sym_operator_character_set_1, 53, lookahead)) ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(35);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(33);
      END_STATE();
    case 10:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 25,
        '#', 16,
        '\'', 40,
        '(', 22,
        ')', 20,
        ',', 21,
        '-', 43,
        ':', 17,
        '[', 45,
        ']', 46,
        '`', 18,
        '{', 28,
        '}', 30,
        0xd7, 37,
        0xf7, 37,
        0x3c0, 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (set_contains(sym_operator_character_set_1, 53, lookahead)) ADVANCE(44);
      if (('$' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z') ||
          (0xc0 <= lookahead && lookahead <= 0x2af) ||
          (0x370 <= lookahead && lookahead <= 0x4ff) ||
          (0x1f00 <= lookahead && lookahead <= 0x1fff) ||
          lookahead == 0x2022) ADVANCE(39);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 25,
        '#', 16,
        '\'', 40,
        '(', 19,
        ')', 20,
        ',', 21,
        '-', 43,
        '.', 32,
        ':', 17,
        '[', 45,
        '\\', 8,
        ']', 46,
        '_', 38,
        '`', 18,
        '{', 29,
        '}', 30,
        0x2022, 38,
        0xd7, 37,
        0xf7, 37,
        0x3c0, 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (set_contains(sym_operator_character_set_1, 53, lookahead)) ADVANCE(44);
      if (('$' <= lookahead && lookahead <= 'z') ||
          (0xc0 <= lookahead && lookahead <= 0x2af) ||
          (0x370 <= lookahead && lookahead <= 0x4ff) ||
          (0x1f00 <= lookahead && lookahead <= 0x1fff)) ADVANCE(39);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 25,
        '#', 16,
        '\'', 40,
        '(', 19,
        ')', 20,
        ',', 21,
        '-', 43,
        ':', 17,
        '[', 45,
        ']', 46,
        '`', 18,
        '{', 28,
        '}', 30,
        0xd7, 37,
        0xf7, 37,
        0x3c0, 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (set_contains(sym_operator_character_set_1, 53, lookahead)) ADVANCE(44);
      if (('$' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z') ||
          (0xc0 <= lookahead && lookahead <= 0x2af) ||
          (0x370 <= lookahead && lookahead <= 0x4ff) ||
          (0x1f00 <= lookahead && lookahead <= 0x1fff) ||
          lookahead == 0x2022) ADVANCE(39);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\'') ADVANCE(16);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(42);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(27);
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(16);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '#') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_interpolation_content_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_format_spec);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '!' ||
          lookahead == '*' ||
          lookahead == '-' ||
          lookahead == 0xd7 ||
          lookahead == 0xf7 ||
          lookahead == 0x3c0) ADVANCE(37);
      if (set_contains(sym_identifier_character_set_2, 13, lookahead)) ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (set_contains(sym_identifier_character_set_2, 13, lookahead)) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (set_contains(sym_identifier_character_set_2, 13, lookahead)) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_quoted_identifier_token1);
      if (lookahead == '#') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_quoted_identifier_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (set_contains(sym_operator_character_set_1, 53, lookahead)) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_operator);
      if (set_contains(sym_operator_character_set_1, 53, lookahead)) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 12},
  [42] = {.lex_state = 12},
  [43] = {.lex_state = 12},
  [44] = {.lex_state = 12},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 12},
  [50] = {.lex_state = 12},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 12},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 12},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 12},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 4},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 5},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_interpolation_content_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [aux_sym_escape_sequence_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [aux_sym_anaphor_token1] = ACTIONS(1),
    [aux_sym_anaphor_token2] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym__declaration_end] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(108),
    [sym_unit_metadata] = STATE(36),
    [sym_declaration] = STATE(44),
    [sym_metadata] = STATE(53),
    [sym_declaration_head] = STATE(107),
    [sym_operator_declaration] = STATE(106),
    [sym_string] = STATE(61),
    [sym_quoted_identifier] = STATE(69),
    [sym_block] = STATE(61),
    [aux_sym_source_file_repeat1] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_BQUOTE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(24), 1,
      anon_sym_COLON,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 1,
      sym_number,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_LBRACE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(42), 1,
      sym_operator,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(2), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
    ACTIONS(19), 6,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [58] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(62), 1,
      sym_operator,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(49), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    ACTIONS(48), 4,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(5), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [117] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(62), 1,
      sym_operator,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(50), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    ACTIONS(66), 4,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(5), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [176] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_SQUOTE,
    ACTIONS(79), 1,
      sym_operator,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    ACTIONS(68), 4,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(2), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [232] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(79), 1,
      sym_operator,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    ACTIONS(68), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(2), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [287] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      sym_operator,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(74), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(6), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [343] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      sym_operator,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(75), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(6), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [399] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      sym_operator,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(74), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(6), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [455] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      sym_operator,
    ACTIONS(89), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(73), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(6), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [511] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      sym_operator,
    ACTIONS(91), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(74), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(6), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [567] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      sym_operator,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(105), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(6), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [623] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      sym_operator,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(74), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(6), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [679] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      sym_number,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      sym_operator,
    STATE(20), 1,
      sym_quoted_identifier,
    STATE(74), 1,
      sym_soup,
    STATE(25), 2,
      sym_string,
      sym_symbol,
    STATE(15), 3,
      sym_paren_expr,
      sym_name,
      sym_block,
    STATE(6), 5,
      sym__element,
      sym_application,
      sym_literal,
      sym_list,
      aux_sym_soup_repeat1,
  [732] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LPAREN2,
    STATE(24), 1,
      sym_argument_list,
    ACTIONS(99), 2,
      anon_sym_LPAREN,
      sym_operator,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [761] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_LPAREN,
      sym_operator,
    ACTIONS(103), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [785] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      anon_sym_LPAREN,
      sym_operator,
    ACTIONS(107), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [809] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      anon_sym_LPAREN,
      sym_operator,
    ACTIONS(111), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [833] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_LPAREN,
      sym_operator,
    ACTIONS(115), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [857] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_LPAREN,
      sym_operator,
    ACTIONS(119), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [881] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_LPAREN,
      sym_operator,
    ACTIONS(123), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [905] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_operator,
    ACTIONS(127), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [928] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_operator,
    ACTIONS(131), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [951] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_operator,
    ACTIONS(135), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [974] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_operator,
    ACTIONS(139), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_operator,
    ACTIONS(123), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1020] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_operator,
    ACTIONS(143), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1043] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_operator,
    ACTIONS(147), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1066] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_operator,
    ACTIONS(151), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1089] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_operator,
    ACTIONS(155), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1112] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_operator,
    ACTIONS(159), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1135] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_operator,
    ACTIONS(163), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1158] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_operator,
    ACTIONS(167), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1181] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_operator,
    ACTIONS(171), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1204] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_operator,
    ACTIONS(175), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1227] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
    STATE(53), 1,
      sym_metadata,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
    STATE(40), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [1262] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(43), 1,
      aux_sym_block_repeat1,
    STATE(53), 1,
      sym_metadata,
    STATE(58), 1,
      sym_declaration,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
  [1299] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_block_repeat1,
    STATE(53), 1,
      sym_metadata,
    STATE(58), 1,
      sym_declaration,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
  [1336] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(190), 1,
      anon_sym_BQUOTE,
    ACTIONS(193), 1,
      anon_sym_LPAREN,
    ACTIONS(196), 1,
      anon_sym_SQUOTE,
    STATE(53), 1,
      sym_metadata,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
    STATE(39), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [1371] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    STATE(53), 1,
      sym_metadata,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
    STATE(39), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [1406] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      aux_sym_block_repeat1,
    STATE(53), 1,
      sym_metadata,
    STATE(58), 1,
      sym_declaration,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
  [1443] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_identifier,
    ACTIONS(206), 1,
      anon_sym_BQUOTE,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    ACTIONS(214), 1,
      anon_sym_SQUOTE,
    STATE(42), 1,
      aux_sym_block_repeat1,
    STATE(53), 1,
      sym_metadata,
    STATE(58), 1,
      sym_declaration,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
  [1480] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      aux_sym_block_repeat1,
    STATE(53), 1,
      sym_metadata,
    STATE(58), 1,
      sym_declaration,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
  [1517] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_BQUOTE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
    STATE(53), 1,
      sym_metadata,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(106), 1,
      sym_operator_declaration,
    STATE(107), 1,
      sym_declaration_head,
    STATE(39), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [1552] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    ACTIONS(223), 1,
      aux_sym_interpolation_content_token1,
    ACTIONS(225), 1,
      sym_format_spec,
    STATE(86), 1,
      sym_interpolation_content,
    ACTIONS(227), 2,
      aux_sym_anaphor_token1,
      aux_sym_anaphor_token2,
    STATE(80), 2,
      sym_dotted_reference,
      sym_anaphor,
  [1579] = 6,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    ACTIONS(233), 1,
      sym_string_content,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    ACTIONS(237), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_escape_sequence_token1,
    STATE(48), 3,
      sym_interpolation,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [1602] = 6,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_DQUOTE,
    ACTIONS(241), 1,
      sym_string_content,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(247), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_escape_sequence_token1,
    STATE(47), 3,
      sym_interpolation,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [1625] = 6,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    ACTIONS(250), 1,
      anon_sym_DQUOTE,
    ACTIONS(252), 1,
      sym_string_content,
    ACTIONS(237), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_escape_sequence_token1,
    STATE(47), 3,
      sym_interpolation,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [1648] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
  [1661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 7,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
  [1674] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      anon_sym_COLON,
    STATE(71), 4,
      sym__meta_value,
      sym_string,
      sym_symbol,
      sym_block,
  [1693] = 2,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(256), 6,
      anon_sym_DQUOTE,
      sym_string_content,
      anon_sym_LBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_escape_sequence_token1,
  [1705] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    STATE(69), 1,
      sym_quoted_identifier,
    STATE(97), 1,
      sym_declaration_head,
    STATE(106), 1,
      sym_operator_declaration,
  [1727] = 2,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(258), 6,
      anon_sym_DQUOTE,
      sym_string_content,
      anon_sym_LBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_escape_sequence_token1,
  [1739] = 2,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(260), 6,
      anon_sym_DQUOTE,
      sym_string_content,
      anon_sym_LBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_escape_sequence_token1,
  [1751] = 2,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(262), 6,
      anon_sym_DQUOTE,
      sym_string_content,
      anon_sym_LBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_escape_sequence_token1,
  [1763] = 2,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(264), 6,
      anon_sym_DQUOTE,
      sym_string_content,
      anon_sym_LBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_escape_sequence_token1,
  [1775] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(266), 5,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
  [1789] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_SQUOTE,
  [1800] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 5,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
  [1811] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 5,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_SQUOTE,
  [1822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_SQUOTE,
  [1833] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_DOT,
    STATE(63), 1,
      aux_sym_dotted_reference_repeat1,
    ACTIONS(272), 2,
      anon_sym_RBRACE,
      sym_format_spec,
  [1847] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_DOT,
    STATE(65), 1,
      aux_sym_dotted_reference_repeat1,
    ACTIONS(277), 2,
      anon_sym_RBRACE,
      sym_format_spec,
  [1861] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_DOT,
    STATE(63), 1,
      aux_sym_dotted_reference_repeat1,
    ACTIONS(281), 2,
      anon_sym_RBRACE,
      sym_format_spec,
  [1875] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(283), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1889] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_parameter_list_repeat1,
  [1902] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_parameter_list_repeat1,
  [1915] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_COLON,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
    STATE(90), 1,
      sym_parameter_list,
  [1928] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(301), 1,
      sym_identifier,
    STATE(22), 1,
      sym_quoted_identifier,
  [1941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 3,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_SQUOTE,
  [1950] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    ACTIONS(305), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_argument_list_repeat1,
  [1963] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      aux_sym_argument_list_repeat1,
  [1976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1985] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
    ACTIONS(313), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_argument_list_repeat1,
  [1998] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
    ACTIONS(317), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_parameter_list_repeat1,
  [2011] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    ACTIONS(319), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_argument_list_repeat1,
  [2024] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 3,
      anon_sym_RBRACE,
      anon_sym_DOT,
      sym_format_spec,
  [2033] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      sym_identifier,
    ACTIONS(323), 1,
      sym_operator,
  [2043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 2,
      anon_sym_RBRACE,
      sym_format_spec,
  [2051] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      sym_identifier,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
  [2061] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
    ACTIONS(331), 1,
      anon_sym_RPAREN,
  [2071] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2079] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_identifier,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
  [2089] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_identifier,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
  [2099] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_RBRACE,
    ACTIONS(343), 1,
      sym_format_spec,
  [2109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 2,
      anon_sym_RBRACE,
      sym_format_spec,
  [2117] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    ACTIONS(333), 1,
      sym_identifier,
  [2127] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_RBRACE,
  [2134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_COLON,
  [2141] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_COLON,
  [2148] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_identifier,
  [2155] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
  [2162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_COLON,
  [2169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_COLON,
  [2176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_COLON,
  [2183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_COLON,
  [2190] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_SQUOTE,
  [2197] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      anon_sym_RBRACE,
  [2204] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      sym_identifier,
  [2211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      anon_sym_COLON,
  [2218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_COLON,
  [2225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      sym_operator,
  [2232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      anon_sym_COLON,
  [2239] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_RPAREN,
  [2246] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_COLON,
  [2253] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      anon_sym_COLON,
  [2260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      ts_builtin_sym_end,
  [2267] = 2,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(381), 1,
      aux_sym_quoted_identifier_token1,
  [2274] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      anon_sym_RPAREN,
  [2281] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 1,
      anon_sym_SQUOTE,
  [2288] = 2,
    ACTIONS(229), 1,
      sym_comment,
    ACTIONS(387), 1,
      aux_sym_quoted_identifier_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 58,
  [SMALL_STATE(4)] = 117,
  [SMALL_STATE(5)] = 176,
  [SMALL_STATE(6)] = 232,
  [SMALL_STATE(7)] = 287,
  [SMALL_STATE(8)] = 343,
  [SMALL_STATE(9)] = 399,
  [SMALL_STATE(10)] = 455,
  [SMALL_STATE(11)] = 511,
  [SMALL_STATE(12)] = 567,
  [SMALL_STATE(13)] = 623,
  [SMALL_STATE(14)] = 679,
  [SMALL_STATE(15)] = 732,
  [SMALL_STATE(16)] = 761,
  [SMALL_STATE(17)] = 785,
  [SMALL_STATE(18)] = 809,
  [SMALL_STATE(19)] = 833,
  [SMALL_STATE(20)] = 857,
  [SMALL_STATE(21)] = 881,
  [SMALL_STATE(22)] = 905,
  [SMALL_STATE(23)] = 928,
  [SMALL_STATE(24)] = 951,
  [SMALL_STATE(25)] = 974,
  [SMALL_STATE(26)] = 997,
  [SMALL_STATE(27)] = 1020,
  [SMALL_STATE(28)] = 1043,
  [SMALL_STATE(29)] = 1066,
  [SMALL_STATE(30)] = 1089,
  [SMALL_STATE(31)] = 1112,
  [SMALL_STATE(32)] = 1135,
  [SMALL_STATE(33)] = 1158,
  [SMALL_STATE(34)] = 1181,
  [SMALL_STATE(35)] = 1204,
  [SMALL_STATE(36)] = 1227,
  [SMALL_STATE(37)] = 1262,
  [SMALL_STATE(38)] = 1299,
  [SMALL_STATE(39)] = 1336,
  [SMALL_STATE(40)] = 1371,
  [SMALL_STATE(41)] = 1406,
  [SMALL_STATE(42)] = 1443,
  [SMALL_STATE(43)] = 1480,
  [SMALL_STATE(44)] = 1517,
  [SMALL_STATE(45)] = 1552,
  [SMALL_STATE(46)] = 1579,
  [SMALL_STATE(47)] = 1602,
  [SMALL_STATE(48)] = 1625,
  [SMALL_STATE(49)] = 1648,
  [SMALL_STATE(50)] = 1661,
  [SMALL_STATE(51)] = 1674,
  [SMALL_STATE(52)] = 1693,
  [SMALL_STATE(53)] = 1705,
  [SMALL_STATE(54)] = 1727,
  [SMALL_STATE(55)] = 1739,
  [SMALL_STATE(56)] = 1751,
  [SMALL_STATE(57)] = 1763,
  [SMALL_STATE(58)] = 1775,
  [SMALL_STATE(59)] = 1789,
  [SMALL_STATE(60)] = 1800,
  [SMALL_STATE(61)] = 1811,
  [SMALL_STATE(62)] = 1822,
  [SMALL_STATE(63)] = 1833,
  [SMALL_STATE(64)] = 1847,
  [SMALL_STATE(65)] = 1861,
  [SMALL_STATE(66)] = 1875,
  [SMALL_STATE(67)] = 1889,
  [SMALL_STATE(68)] = 1902,
  [SMALL_STATE(69)] = 1915,
  [SMALL_STATE(70)] = 1928,
  [SMALL_STATE(71)] = 1941,
  [SMALL_STATE(72)] = 1950,
  [SMALL_STATE(73)] = 1963,
  [SMALL_STATE(74)] = 1976,
  [SMALL_STATE(75)] = 1985,
  [SMALL_STATE(76)] = 1998,
  [SMALL_STATE(77)] = 2011,
  [SMALL_STATE(78)] = 2024,
  [SMALL_STATE(79)] = 2033,
  [SMALL_STATE(80)] = 2043,
  [SMALL_STATE(81)] = 2051,
  [SMALL_STATE(82)] = 2061,
  [SMALL_STATE(83)] = 2071,
  [SMALL_STATE(84)] = 2079,
  [SMALL_STATE(85)] = 2089,
  [SMALL_STATE(86)] = 2099,
  [SMALL_STATE(87)] = 2109,
  [SMALL_STATE(88)] = 2117,
  [SMALL_STATE(89)] = 2127,
  [SMALL_STATE(90)] = 2134,
  [SMALL_STATE(91)] = 2141,
  [SMALL_STATE(92)] = 2148,
  [SMALL_STATE(93)] = 2155,
  [SMALL_STATE(94)] = 2162,
  [SMALL_STATE(95)] = 2169,
  [SMALL_STATE(96)] = 2176,
  [SMALL_STATE(97)] = 2183,
  [SMALL_STATE(98)] = 2190,
  [SMALL_STATE(99)] = 2197,
  [SMALL_STATE(100)] = 2204,
  [SMALL_STATE(101)] = 2211,
  [SMALL_STATE(102)] = 2218,
  [SMALL_STATE(103)] = 2225,
  [SMALL_STATE(104)] = 2232,
  [SMALL_STATE(105)] = 2239,
  [SMALL_STATE(106)] = 2246,
  [SMALL_STATE(107)] = 2253,
  [SMALL_STATE(108)] = 2260,
  [SMALL_STATE(109)] = 2267,
  [SMALL_STATE(110)] = 2274,
  [SMALL_STATE(111)] = 2281,
  [SMALL_STATE(112)] = 2288,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_soup_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_soup, 1, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_soup, 1, 0, 0), SHIFT(20),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_soup, 1, 0, 0), SHIFT(12),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_soup, 1, 0, 0), SHIFT(112),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__element, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__element, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_identifier, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_identifier, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 5, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [241] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [244] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [247] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 4, 0, 1),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_metadata, 1, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_reference_repeat1, 2, 0, 0),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation_content, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_reference, 2, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_head, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 2, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [323] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anaphor, 1, 0, 0),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_head, 2, 0, 0),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 5, 0, 0),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_declaration, 3, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_declaration, 5, 0, 0),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_declaration, 4, 0, 0),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [379] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [381] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [387] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__declaration_end = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__declaration_end] = sym__declaration_end,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__declaration_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_eucalypt_external_scanner_create(void);
void tree_sitter_eucalypt_external_scanner_destroy(void *);
bool tree_sitter_eucalypt_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_eucalypt_external_scanner_serialize(void *, char *);
void tree_sitter_eucalypt_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_eucalypt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_eucalypt_external_scanner_create,
      tree_sitter_eucalypt_external_scanner_destroy,
      tree_sitter_eucalypt_external_scanner_scan,
      tree_sitter_eucalypt_external_scanner_serialize,
      tree_sitter_eucalypt_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
