pub mod error;
#[cfg(not(target_arch = "wasm32"))]
pub mod eval;
#[cfg(not(target_arch = "wasm32"))]
pub mod format;
pub mod io;
#[cfg(not(target_arch = "wasm32"))]
pub mod lsp;
#[cfg(not(target_arch = "wasm32"))]
pub mod options;
#[cfg(not(target_arch = "wasm32"))]
pub mod prepare;
#[cfg(not(target_arch = "wasm32"))]
pub mod project;
pub mod resources;
#[cfg(not(target_arch = "wasm32"))]
pub mod source;
pub mod statistics;
#[cfg(not(target_arch = "wasm32"))]
pub mod tester;
