name: Eucalypt Build Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      narrative:
        description: 'Reason for build'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Install latest eucalypt
      run: |
          pip install pipenv
          mkdir bin
          cd ci
          pipenv install
          pipenv run python fetch.py $GITHUB_WORKSPACE/bin
          echo "::add-path::$GITHUB_WORKSPACE/bin"
          $GITHUB_WORKSPACE/bin/eu --version
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.2'
        cabal-version: '3.0'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Add Stack paths to environment
      run: |
          echo "::set-env name=STACK_DIST_DIR::$(stack path --dist-dir)"

    - name: Install dependencies
      run: stack build --fast --pedantic --no-terminal --install-ghc --only-dependencies

    - name: Install HLint
      run: stack install --no-terminal hlint

    - name: Update build metadata in package.yaml
      run: |
        export OSTYPE=$(uname)
        export HOSTTYPE=$(uname -m)
        eu ci/build.eu > new-package.yaml
        mv -f new-package.yaml package.yaml
        echo --- replaced package.yaml ---

    - name: Build
      run: stack build --fast --pedantic --no-terminal --test

    - name: Upload binaries
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ${{ env.STACK_DIST_DIR }}

  build-test-harness:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: curvelogic/eucalypt-test-harness
        path: harness
        tag_with_ref: true
        tag_with_sha: true
